[project]
name = "c-two"
version = "0.1.24"
description = "A python server to support communication between CRM and Component processes."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "pyzmq>=27.0.0",
    "requests>=2.32.4",
    "starlette>=0.46.0",
]

[dependency-groups]
dev = [
    "anthropic>=0.49.0",
    "numpy>=2.2.4",
    "openai>=1.76.0",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
]
