[project]
name = "c-two"
version = "0.1.19"
description = "A python server to support communication between CRM and Component processes."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grpcio>=1.71.0",
    "grpcio-tools>=1.71.0",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "mypy-protobuf>=3.6.0",
    "pyarrow>=19.0.1",
    "zmq>=0.0.0",
]

[dependency-groups]
dev = [
    "anthropic>=0.49.0",
    "numpy>=2.2.4",
    "openai>=1.76.0",
    "pandas>=2.2.3",
]
